name: movie_app
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ^3.6.0
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  font_awesome_flutter: ^10.8.0
  google_fonts: ^6.2.1
  provider: ^6.1.2
  shared_preferences: ^2.5.2
  collection: ^1.19.0
  from_css_color: ^2.0.0
  intl: ^0.20.2
  json_path: ^0.7.5
  timeago: 3.2.2
  url_launcher: ^6.3.1
  page_transition: ^2.2.1
  auto_size_text: ^3.0.0
  go_router: ^14.7.2
  firebase_core: ^3.11.0
  firebase_auth: ^5.4.2
  fluttertoast: ^8.2.12
  smooth_page_indicator: ^1.2.0+3
  http: ^1.3.0
  path_provider: ^2.1.5
  expandable: ^5.0.1
  youtube_player_flutter: ^9.1.1
  cloud_firestore: ^5.6.5
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
flutter:
  uses-material-design: true

