// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAFQ8ju-S5y3wrhX-ThjUGbuIY5GkbKZWs',
    appId: '1:1004901029590:web:c9b5fd684fbce1ccf39b77',
    messagingSenderId: '1004901029590',
    projectId: 'authuser-ba081',
    authDomain: 'authuser-ba081.firebaseapp.com',
    storageBucket: 'authuser-ba081.firebasestorage.app',
    measurementId: 'G-E0B147GZCL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAaiQazsz3jwU47boDS4Q-Y8UV2DHGMmXE',
    appId: '1:1004901029590:android:0e6a1f1ea4178e33f39b77',
    messagingSenderId: '1004901029590',
    projectId: 'authuser-ba081',
    storageBucket: 'authuser-ba081.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCpXZXNYaU5TpFfj9SS8pu7-aaHv9l-yuA',
    appId: '1:1004901029590:ios:3be1bf6b2f81ec19f39b77',
    messagingSenderId: '1004901029590',
    projectId: 'authuser-ba081',
    storageBucket: 'authuser-ba081.firebasestorage.app',
    iosBundleId: 'com.example.movieApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCpXZXNYaU5TpFfj9SS8pu7-aaHv9l-yuA',
    appId: '1:1004901029590:ios:3be1bf6b2f81ec19f39b77',
    messagingSenderId: '1004901029590',
    projectId: 'authuser-ba081',
    storageBucket: 'authuser-ba081.firebasestorage.app',
    iosBundleId: 'com.example.movieApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAFQ8ju-S5y3wrhX-ThjUGbuIY5GkbKZWs',
    appId: '1:1004901029590:web:e2584f3d5bd6f15ff39b77',
    messagingSenderId: '1004901029590',
    projectId: 'authuser-ba081',
    authDomain: 'authuser-ba081.firebaseapp.com',
    storageBucket: 'authuser-ba081.firebasestorage.app',
    measurementId: 'G-MGN2J8JHL9',
  );
}
